import { Grievance, Admin, User, Department } from '@/types';

export const mockUsers: User[] = [
  {
    id: 'user-1',
    email: 'john@example.com',
    name: 'John Doe',
    role: 'user',
  },
  {
    id: 'admin-1',
    email: 'admin.water@gov.in',
    name: 'Admin Water Supply',
    role: 'admin',
    department: 'Water Supply',
  },
  {
    id: 'admin-2',
    email: 'admin.sanitation@gov.in',
    name: 'Admin Sanitation',
    role: 'admin',
    department: 'Sanitation & Garbage',
  },
  {
    id: 'super-admin-1',
    email: 'superadmin@gov.in',
    name: 'Super Administrator',
    role: 'super-admin',
  },
];

export const mockGrievances: Grievance[] = [
  {
    id: 'GRV-001',
    userId: 'user-1',
    userName: 'John Doe',
    userPhone: '+91 9876543210',
    userEmail: 'john@example.com',
    userAddress: '123 Main Street, Block A, New Delhi - 110001',
    department: 'Water Supply',
    title: 'No water supply for 3 days',
    description: 'There has been no water supply in our area for the past 3 days. Multiple residents are facing severe water shortage. Please take immediate action.',
    urgency: 'High',
    status: 'In Progress',
    createdAt: '2026-02-20T10:30:00Z',
    updatedAt: '2026-02-22T14:20:00Z',
    assignedTo: 'admin-1',
    responses: [
      {
        id: 'resp-1',
        grievanceId: 'GRV-001',
        userId: 'admin-1',
        userName: 'Admin Water Supply',
        userRole: 'admin',
        message: 'We have received your complaint. Our team is inspecting the water supply lines in your area. We expect to resolve this within 24 hours.',
        createdAt: '2026-02-22T14:20:00Z',
      },
    ],
    timeline: [
      {
        id: 'tl-1',
        status: 'Submitted',
        description: 'Grievance submitted by user',
        timestamp: '2026-02-20T10:30:00Z',
        userId: 'user-1',
        userName: 'John Doe',
      },
      {
        id: 'tl-2',
        status: 'Assigned',
        description: 'Assigned to Water Supply Department',
        timestamp: '2026-02-20T11:00:00Z',
      },
      {
        id: 'tl-3',
        status: 'In Progress',
        description: 'Team dispatched for inspection',
        timestamp: '2026-02-22T14:20:00Z',
        userId: 'admin-1',
        userName: 'Admin Water Supply',
      },
    ],
  },
  {
    id: 'GRV-002',
    userId: 'user-1',
    userName: 'John Doe',
    userPhone: '+91 9876543210',
    userEmail: 'john@example.com',
    userAddress: '123 Main Street, Block A, New Delhi - 110001',
    department: 'Sanitation & Garbage',
    title: 'Garbage not collected for a week',
    description: 'Garbage collection has been irregular and has not been done for the past week. This is causing unhygienic conditions in the neighborhood.',
    urgency: 'Medium',
    status: 'Solved',
    createdAt: '2026-02-15T09:00:00Z',
    updatedAt: '2026-02-18T16:30:00Z',
    assignedTo: 'admin-2',
    responses: [
      {
        id: 'resp-2',
        grievanceId: 'GRV-002',
        userId: 'admin-2',
        userName: 'Admin Sanitation',
        userRole: 'admin',
        message: 'Your complaint has been resolved. Regular garbage collection has been resumed.',
        createdAt: '2026-02-18T16:30:00Z',
      },
    ],
    timeline: [
      {
        id: 'tl-4',
        status: 'Submitted',
        description: 'Grievance submitted by user',
        timestamp: '2026-02-15T09:00:00Z',
        userId: 'user-1',
        userName: 'John Doe',
      },
      {
        id: 'tl-5',
        status: 'Assigned',
        description: 'Assigned to Sanitation Department',
        timestamp: '2026-02-15T10:00:00Z',
      },
      {
        id: 'tl-6',
        status: 'In Progress',
        description: 'Sanitation team dispatched',
        timestamp: '2026-02-16T08:00:00Z',
        userId: 'admin-2',
        userName: 'Admin Sanitation',
      },
      {
        id: 'tl-7',
        status: 'Resolved',
        description: 'Issue resolved, regular collection resumed',
        timestamp: '2026-02-18T16:30:00Z',
        userId: 'admin-2',
        userName: 'Admin Sanitation',
      },
    ],
  },
  {
    id: 'GRV-003',
    userId: 'user-1',
    userName: 'John Doe',
    userPhone: '+91 9876543210',
    userEmail: 'john@example.com',
    userAddress: '123 Main Street, Block A, New Delhi - 110001',
    department: 'Roads & Drainage',
    title: 'Pothole on main road',
    description: 'Large pothole on the main road near sector 12 market causing traffic issues and accidents.',
    urgency: 'High',
    status: 'Unsolved',
    createdAt: '2026-02-24T11:00:00Z',
    updatedAt: '2026-02-24T11:00:00Z',
    responses: [],
    timeline: [
      {
        id: 'tl-8',
        status: 'Submitted',
        description: 'Grievance submitted by user',
        timestamp: '2026-02-24T11:00:00Z',
        userId: 'user-1',
        userName: 'John Doe',
      },
    ],
  },
  {
    id: 'GRV-004',
    userId: 'user-1',
    userName: 'John Doe',
    userPhone: '+91 9876543210',
    userEmail: 'john@example.com',
    userAddress: '123 Main Street, Block A, New Delhi - 110001',
    department: 'Electricity',
    title: 'Frequent power cuts',
    description: 'Experiencing frequent and unscheduled power cuts multiple times a day for the past week.',
    urgency: 'Medium',
    status: 'In Progress',
    createdAt: '2026-02-23T15:30:00Z',
    updatedAt: '2026-02-25T10:00:00Z',
    responses: [],
    timeline: [
      {
        id: 'tl-9',
        status: 'Submitted',
        description: 'Grievance submitted by user',
        timestamp: '2026-02-23T15:30:00Z',
        userId: 'user-1',
        userName: 'John Doe',
      },
      {
        id: 'tl-10',
        status: 'In Progress',
        description: 'Electricity board notified',
        timestamp: '2026-02-25T10:00:00Z',
      },
    ],
  },
  {
    id: 'GRV-005',
    userId: 'user-1',
    userName: 'John Doe',
    userPhone: '+91 9876543210',
    userEmail: 'john@example.com',
    userAddress: '123 Main Street, Block A, New Delhi - 110001',
    department: 'Public Health',
    title: 'Stray dogs creating nuisance',
    description: 'Large number of stray dogs in the area creating safety concerns, especially for children.',
    urgency: 'Low',
    status: 'Unsolved',
    createdAt: '2026-02-19T08:00:00Z',
    updatedAt: '2026-02-19T08:00:00Z',
    responses: [],
    timeline: [
      {
        id: 'tl-11',
        status: 'Submitted',
        description: 'Grievance submitted by user',
        timestamp: '2026-02-19T08:00:00Z',
        userId: 'user-1',
        userName: 'John Doe',
      },
    ],
  },
];

export const mockAdmins: Admin[] = [
  {
    id: 'admin-1',
    email: 'admin.water@gov.in',
    name: 'Admin Water Supply',
    department: 'Water Supply',
    isActive: true,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'admin-2',
    email: 'admin.sanitation@gov.in',
    name: 'Admin Sanitation',
    department: 'Sanitation & Garbage',
    isActive: true,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'admin-3',
    email: 'admin.roads@gov.in',
    name: 'Admin Roads',
    department: 'Roads & Drainage',
    isActive: true,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'admin-4',
    email: 'admin.electricity@gov.in',
    name: 'Admin Electricity',
    department: 'Electricity',
    isActive: false,
    createdAt: '2026-01-01T00:00:00Z',
  },
];

export const departments: Department[] = [
  'Water Supply',
  'Sanitation & Garbage',
  'Roads & Drainage',
  'Electricity',
  'Public Health',
  'Police & Law Enforcement',
  'Housing & Building Issues',
  'General / Miscellaneous',
];
